Advertising: 24.75
Aerospace/Defense: 29.23
Air Transport: 27.68
Apparel: 15.36
Auto & Truck: 18.3
Auto Parts: 15.49
Beverage (Alcoholic): 34.2
Beverage (Soft): 19.49
Broadcasting: 9.31
Brokerage & Investment Banking: 182.48
Building Materials: 15.64
Business & Consumer Services: 20.35
Cable TV: 8.47
Chemical (Basic): 15.73
Chemical (Diversified): 13.27
Chemical (Specialty): 16.97
Coal & Related Energy: 5.37
Computer Services: 18.47
Computers/Peripherals: 10.63
Construction Supplies: 9.22
Diversified: 8.76
Drugs (Biotechnology): 46.63
Drugs (Pharmaceutical): 21.15
Education: 32.85
Electrical Equipment: 25.85
Electronics (Consumer & Office): 13.65
Electronics (General): 17.77
Engineering/Construction: 7.85
Entertainment: 24.3
Environmental & Waste Services: 13.74
Farming/Agriculture: 13.26
Financial Svcs. (Non-bank & Insurance): 20.5
Food Processing: 14.63
Food Wholesalers: 13.36
Furn/Home Furnishings: 19.04
Green & Renewable Energy: 13.33
Healthcare Products: 24.65
Healthcare Support Services: 15.74
Heathcare Information and Technology: 109.07
Homebuilding: 12.08
Hospitals/Healthcare Facilities: 33.24
Hotel/Gaming: 30.15
Household Products: 24.51
Information Services: 17.39
Insurance (General): 10.08
Insurance (Life): 10.47
Insurance (Prop/Cas.): 8.56
Investments & Asset Management: 15.87
Machinery: 23.82
Metals & Mining: 12.38
Office Equipment & Services: 25.62
Oil/Gas (Integrated): 10.26
Oil/Gas (Production and Exploration): 6.13
Oil/Gas Distribution: 7.33
Oilfield Svcs/Equip.: 14.27
Packaging & Container: 13.59
Paper/Forest Products: 11.33
Power: 8.49
Precious Metals: 10.93
Publishing & Newspapers: 15.22
R.E.I.T.: 21.67
Real Estate (Development): 9.34
Real Estate (General/Diversified): 14.96
Real Estate (Operations & Services): 19.51
Recreation: 14.49
Reinsurance: 9.43
Restaurant/Dining: 28.69
Retail (Automotive): 13.64
Retail (Building Supply): 21.89
Retail (Distributors): 12.31
Retail (General): 14.88
Retail (Grocery and Food): 14.67
Retail (Online): 41.66
Retail (Special Lines): 19.37
Rubber& Tires: 9.54
Semiconductor: 17.52
Semiconductor Equip: 25.39
Shipbuilding & Marine: 12.23
Shoe: 27.56
Software (Entertainment): 27.96
Software (Internet): 38.22
Software (System & Application): 48.51
Steel: 8.6
Telecom (Wireless): 5.49
Telecom. Equipment: 27.87
Telecom. Services: 6.09
Tobacco: 14.6
Total Market: 14.21
Total Market (without financials): 13.39
Transportation: 13.7
Transportation (Railroads): 14.12
Trucking: 10.61
Utility (General): 12.32
Utility (Water): 9.86
