Advertising: 2.23
Aerospace/Defense: 2.72
Air Transport: 1.5
Apparel: 1.22
Auto & Truck: 1.26
Auto Parts: 1.24
Bank (Money Center): 3.34
Banks (Regional): 3.58
Beverage (Alcoholic): 10.5
Beverage (Soft): 2.67
Broadcasting: 2.01
Brokerage & Investment Banking: 4.03
Building Materials: 2.05
Business & Consumer Services: 2.01
Cable TV: 2.1
Chemical (Basic): 1.72
Chemical (Diversified): 1.77
Chemical (Specialty): 2.34
Coal & Related Energy: 0.93
Computer Services: 1.49
Computers/Peripherals: 1.28
Construction Supplies: 1.27
Diversified: 0.6
Drugs (Biotechnology): 18.45
Drugs (Pharmaceutical): 3.57
Education: 7.19
Electrical Equipment: 2.41
Electronics (Consumer & Office): 0.74
Electronics (General): 1.66
Engineering/Construction: 0.29
Entertainment: 6.41
Environmental & Waste Services: 2.42
Farming/Agriculture: 1.17
Financial Svcs. (Non-bank & Insurance): 4.31
Food Processing: 1.65
Food Wholesalers: 0.44
Furn/Home Furnishings: 2.0
Green & Renewable Energy: 5.28
Healthcare Products: 8.44
Healthcare Support Services: 0.89
Healthcare Information and Technology: 22.11
Homebuilding: 1.62
Hospitals/Healthcare Facilities: 5.96
Hotel/Gaming: 3.11
Household Products: 4.33
Information Services: 4.63
Insurance (General): 1.01
Insurance (Life): 1.06
Insurance (Prop/Cas.): 0.46
Investments & Asset Management: 2.7
Machinery: 2.51
Metals & Mining: 1.19
Office Equipment & Services: 2.51
Oil/Gas (Integrated): 1.77
Oil/Gas (Production and Exploration): 1.91
Oil/Gas Distribution: 0.81
Oilfield Svcs/Equip: 0.81
Packaging & Container: 1.66
Paper/Forest Products: 1.22
Power: 1.12
Precious Metals: 2.21
Publishing & Newspapers: 1.95
R.E.I.T.: 13.53
Real Estate (Development): 0.84
Real Estate (General/Diversified): 2.71
Real Estate (Operations & Services): 4.99
Recreation: 2.32
Reinsurance: 0.66
Restaurant/Dining: 3.04
Retail (Automotive): 0.59
Retail (Building Supply): 2.06
Retail (Distributors): 0.31
Retail (General): 0.94
Retail (Grocery and Food): 0.78
Retail (Online): 5.7
Retail (Special Lines): 1.5
Rubber & Tires: 1.19
Semiconductor: 5.3
Semiconductor Equip: 4.79
Shipbuilding & Marine: 1.72
Shoe: 2.25
Software (Entertainment): 7.98
Software (Internet): 3.78
Software (System & Application): 7.31
Steel: 0.79
Telecom (Wireless): 1.27
Telecom. Equipment: 2.24
Telecom. Services: 1.36
Tobacco: 4.6
Transportation: 1.22
Transportation (Railroads): 3.58
Trucking: 1.2
Utility (General): 3.76
Utility (Water): 2.15
